### ISSUE TITLE
Newline in message prevent tag keyword detection

### ISSUE THREAD

**Issue by Bric3d** [Kronicaler/markov-bot#56]
**Describe the bug**
A message including a newline character will not trigger the keyword recognition and in turn not display the associated tag

**To Reproduce**
Create a tag, eg `/tag create test 'this is a test'`
Try to trigger tag with message such as
```
this
is a test
```

**Expected behavior**
The example above should trigger the bot to repeated the tag associated with the `test` keyword.

**Comment by Kronicaler** [comment]
Fixed in de180e3745c1d1c50203e3c5afae8189c861b239
